! Define variables to valuate stencil coefficients, dim=2, order=6, gridType=Rectangular
! File generated by cgWave/maple/writeStencilFiles.mpl
integer i1m3,i1m2,i1m1,i1p1,i1p2,i1p3
integer i2m3,i2m2,i2m1,i2p1,i2p2,i2p3
real t0,t1,t4,t9,t14,t15,t16,t17,t18,t19,t21,t23,t24,t25,t28,t32,t33,t37,t42,t45,t46,t47,t49,t50,t51,t53,t59,t64,t67,t68,t69\
    ,t70,t72,t73,t75,t76,t78,t79,t90,t93,t98,t99,t101,t104,t111,t119,t122,t123,t124,t126,t143,t144;
