! Define variables to valuate stencil coefficients, dim=2, order=4, gridType=Curvilinear
! File generated by cgWave/maple/writeStencilFiles.mpl
integer i1m3,i1m2,i1m1,i1p1,i1p2,i1p3
integer i2m3,i2m2,i2m1,i2p1,i2p2,i2p3
real t0,t1,t2,t6,t7,t9,t10,t12,t13,t14,t15,t16,t22,t23,t27,t28,t29,t32,t33,t36,t43,t44,t45,t46,t56,t57,t59,t60,t62,t63,t64\
    ,t65,t66,t73,t74,t75,t76,t77,t80,t81,t82,t85,t86,t89,t90,t99,t100,t101,t102,t106,t110,t112,t113,t114,t122,t123,t127,t128,t129,t134,t135\
    ,t147,t149,t158,t161,t162,t163,t164,t167,t174,t175,t176,t177,t182,t185,t187,t188,t189,t197,t198,t202,t205,t206,t207,t208,t211,t212,t213,t214,t217,t218\
    ,t219,t222,t233,t234,t235,t236,t263,t264,t265,t266,t275,t276,t277,t282,t283,t294,t295,t296,t297,t336,t338;
