! Define variables to valuate stencil coefficients, dim=3, order=2, gridType=Curvilinear
! File generated by cgWave/maple/writeStencilFiles.mpl
integer i1m3,i1m2,i1m1,i1p1,i1p2,i1p3
integer i2m3,i2m2,i2m1,i2p1,i2p2,i2p3
integer i3m3,i3m2,i3m1,i3p1,i3p2,i3p3
real t0,t1,t3,t4,t6,t7,t8,t9,t12,t14,t15,t16,t17,t20,t21,t22;
