! Define variables to valuate stencil coefficients, dim=3, order=4, gridType=Rectangular
! File generated by cgWave/maple/writeStencilFiles.mpl
integer i1m3,i1m2,i1m1,i1p1,i1p2,i1p3
integer i2m3,i2m2,i2m1,i2p1,i2p2,i2p3
integer i3m3,i3m2,i3m1,i3p1,i3p2,i3p3
real t0,t1,t3,t4,t7,t8,t10,t12,t14,t15,t16,t17,t20,t23,t25,t27,t28,t30,t32,t33,t34,t37,t40,t42,t44,t45,t46,t49,t52;
