! Define variables to valuate stencil coefficients, dim=3, order=6, gridType=Rectangular
! File generated by cgWave/maple/writeStencilFiles.mpl
integer i1m3,i1m2,i1m1,i1p1,i1p2,i1p3
integer i2m3,i2m2,i2m1,i2p1,i2p2,i2p3
integer i3m3,i3m2,i3m1,i3p1,i3p2,i3p3
real t0,t1,t5,t9,t11,t12,t13,t16,t17,t18,t19,t22,t23,t25,t26,t27,t28,t29,t30,t31,t33,t34,t37,t39,t43,t44,t45,t46,t47,t50,t54\
    ,t55,t58,t61,t62,t63,t64,t66,t67,t68,t70,t71,t74,t79,t80,t83,t84,t85,t86,t88,t90,t91,t97,t98,t100,t101,t104,t107,t109,t110,t112\
    ,t113,t115,t116,t117,t118,t119,t121,t122,t124,t125,t130,t137,t143,t147,t151,t152,t153,t156,t157,t159,t162,t164,t168,t169,t172,t178,t179,t180,t181,t183\
    ,t189,t190,t194,t197,t198,t199,t201,t203,t204,t209,t216,t220,t224,t225,t227,t230,t232,t238,t245,t248,t249,t251,t253,t258,t274,t275,t276;
