! Evaluate stencil coefficients, dim=2, order=2, gridType=Rectangular
! File generated by cgWave/maple/writeStencilFiles.mpl
t1 = (dt2 * cdy2i);
t2 = (dt2 * cdx2i);
scr(1) = 0;
scr(2) = t1;
scr(3) = 0;
scr(4) = t2;
scr(5) = 2 - 2 * dt2 * (cdy2i + cdx2i);
scr(6) = t2;
scr(7) = 0;
scr(8) = t1;
scr(9) = 0;
