! Evaluate stencil coefficients, dim=2, order=2, gridType=Curvilinear
! File generated by cgWave/maple/writeStencilFiles.mpl
t1 = c11(i1, i2);
t3 = t1 * dt2 / 0.4e1;
t4 = c01(i1, i2);
t5 = t4 / 0.2e1;
t6 = c02(i1, i2);
t9 = c10(i1, i2);
t10 = t9 / 0.2e1;
t11 = c20(i1, i2);
sc(1,i1,i2) = t3;
sc(2,i1,i2) = -dt2 * (t5 - t6);
sc(3,i1,i2) = -t3;
sc(4,i1,i2) = -dt2 * (t10 - t11);
sc(5,i1,i2) = 0.2e1 - 0.2e1 * dt2 * (t6 + t11);
sc(6,i1,i2) = dt2 * (t10 + t11);
sc(7,i1,i2) = -t3;
sc(8,i1,i2) = dt2 * (t5 + t6);
sc(9,i1,i2) = t3;
