cgWave = $(CGWAVE)/bin/cgWave
ogen = $(Overture)/bin/ogen

# small hole in a square
holeGridsRad0p1:
	$(ogen) -noplot smallHoleGrid.cmd -prefix=holeGridRad0p1 -order=2 -rgd=fixed -rad=.1 -factor=2
	$(ogen) -noplot smallHoleGrid.cmd -prefix=holeGridRad0p1 -order=2 -rgd=fixed -rad=.1 -factor=4
	$(ogen) -noplot smallHoleGrid.cmd -prefix=holeGridRad0p1 -order=2 -rgd=fixed -rad=.1 -factor=8
	$(ogen) -noplot smallHoleGrid.cmd -prefix=holeGridRad0p1 -order=2 -rgd=fixed -rad=.1 -factor=16
	$(ogen) -noplot smallHoleGrid.cmd -prefix=holeGridRad0p1 -order=2 -rgd=fixed -rad=.1 -factor=32
	$(ogen) -noplot smallHoleGrid.cmd -prefix=holeGridRad0p1 -order=4 -rgd=fixed -rad=.1 -factor=2 
	$(ogen) -noplot smallHoleGrid.cmd -prefix=holeGridRad0p1 -order=4 -rgd=fixed -rad=.1 -factor=4 
	$(ogen) -noplot smallHoleGrid.cmd -prefix=holeGridRad0p1 -order=4 -rgd=fixed -rad=.1 -factor=8 
	$(ogen) -noplot smallHoleGrid.cmd -prefix=holeGridRad0p1 -order=4 -rgd=fixed -rad=.1 -factor=16
	$(ogen) -noplot smallHoleGrid.cmd -prefix=holeGridRad0p1 -order=4 -rgd=fixed -rad=.1 -factor=32

holeGridsRad0p05:
	$(ogen) -noplot smallHoleGrid.cmd -prefix=holeGridRad0p05 -order=2 -rgd=fixed -rad=.05 -factor=2
	$(ogen) -noplot smallHoleGrid.cmd -prefix=holeGridRad0p05 -order=2 -rgd=fixed -rad=.05 -factor=4
	$(ogen) -noplot smallHoleGrid.cmd -prefix=holeGridRad0p05 -order=2 -rgd=fixed -rad=.05 -factor=8
	$(ogen) -noplot smallHoleGrid.cmd -prefix=holeGridRad0p05 -order=2 -rgd=fixed -rad=.05 -factor=16
	$(ogen) -noplot smallHoleGrid.cmd -prefix=holeGridRad0p05 -order=2 -rgd=fixed -rad=.05 -factor=32
	$(ogen) -noplot smallHoleGrid.cmd -prefix=holeGridRad0p05 -order=4 -rgd=fixed -rad=.05 -factor=2 
	$(ogen) -noplot smallHoleGrid.cmd -prefix=holeGridRad0p05 -order=4 -rgd=fixed -rad=.05 -factor=4 
	$(ogen) -noplot smallHoleGrid.cmd -prefix=holeGridRad0p05 -order=4 -rgd=fixed -rad=.05 -factor=8 
	$(ogen) -noplot smallHoleGrid.cmd -prefix=holeGridRad0p05 -order=4 -rgd=fixed -rad=.05 -factor=16
	$(ogen) -noplot smallHoleGrid.cmd -prefix=holeGridRad0p05 -order=4 -rgd=fixed -rad=.05 -factor=32

holeGridsRad0p01:
	$(ogen) -noplot smallHoleGrid.cmd -prefix=holeGridRad0p01 -order=2 -rgd=fixed -rad=.01 -factor=2
	$(ogen) -noplot smallHoleGrid.cmd -prefix=holeGridRad0p01 -order=2 -rgd=fixed -rad=.01 -factor=4
	$(ogen) -noplot smallHoleGrid.cmd -prefix=holeGridRad0p01 -order=2 -rgd=fixed -rad=.01 -factor=8
	$(ogen) -noplot smallHoleGrid.cmd -prefix=holeGridRad0p01 -order=2 -rgd=fixed -rad=.01 -factor=16
	$(ogen) -noplot smallHoleGrid.cmd -prefix=holeGridRad0p01 -order=2 -rgd=fixed -rad=.01 -factor=32
	$(ogen) -noplot smallHoleGrid.cmd -prefix=holeGridRad0p01 -order=4 -rgd=fixed -rad=.01 -factor=2 
	$(ogen) -noplot smallHoleGrid.cmd -prefix=holeGridRad0p01 -order=4 -rgd=fixed -rad=.01 -factor=4 
	$(ogen) -noplot smallHoleGrid.cmd -prefix=holeGridRad0p01 -order=4 -rgd=fixed -rad=.01 -factor=8 
	$(ogen) -noplot smallHoleGrid.cmd -prefix=holeGridRad0p01 -order=4 -rgd=fixed -rad=.01 -factor=16
	$(ogen) -noplot smallHoleGrid.cmd -prefix=holeGridRad0p01 -order=4 -rgd=fixed -rad=.01 -factor=32
